import { useQuery } from "@tanstack/react-query";
import { GetData } from "../../lib/api/api";

interface ITranslation {
  _id: string;
  grade: number;
  question: string;
  answer: string;
}

const TranslationSheet = () => {
  const { data, isLoading, error } = useQuery<ITranslation[], Error>({
    queryKey: ["translation"],
    queryFn: () => GetData<ITranslation[]>("/api/translation"),
  });

  if (isLoading) return <p className="text-center mt-10">Loading...</p>;
  if (error) return <p className="text-center mt-10 text-red-600">Error: {error.message}</p>;

  return (
    <div className="max-w-4xl mx-auto p-6 bg-white shadow-md rounded-lg mt-6">
      <h1 className="text-3xl font-bold mb-8 text-center">English Practice Sheet</h1>

      {data?.map((item, index) => (
        <div key={item._id} className="mb-8">
          {/* Question Section */}
          <div className="mb-2">
            <span className="font-semibold">{index + 1}. Grade {item.grade}:</span>
            <p className="ml-4 text-base sm:text-lg leading-relaxed">{item.question}</p>
          </div>

          {/* Answer Section */}
          <div className="mb-2">
            <span className="font-semibold">Answer:</span>
            <p className="ml-4 text-base sm:text-lg leading-relaxed">{item.answer}</p>
          </div>

          <hr className="border-t border-gray-300 mt-4" />
        </div>
      ))}

      <p className="text-center mt-10 text-sm text-gray-500">
        Generated by Translation Practice App
      </p>
    </div>
  );
};

export default TranslationSheet;
